export const glossary = [
  { term: 'Check', description: 'Passar a vez sem apostar. Só é possível se ninguém apostou antes de você na rodada.' },
  { term: 'Bet', description: 'Ser o primeiro a colocar fichas no pote em uma rodada de apostas.' },
  { term: 'Call', description: 'Igualar o valor da aposta ou aumento mais recente para continuar na mão.' },
  { term: 'Raise', description: 'Aumentar o valor da aposta atual, forçando os outros a pagar mais ou desistir.' },
  { term: 'Fold', description: 'Desistir da mão, perdendo as fichas já apostadas.' },
  { term: 'All-in', description: 'Apostar todas as suas fichas de uma só vez.' },
  { term: 'Pot', description: 'O total de fichas apostadas em uma mão, que o vencedor leva.' },
  { term: 'Chips', description: 'Discos que representam o dinheiro no jogo.' },
  { term: 'Stack', description: 'Total de fichas que um jogador tem à sua frente.' },
  { term: 'Kicker', description: 'Carta de desempate usada quando jogadores têm mãos iguais.' },
  { term: 'Showdown', description: 'Momento em que os jogadores mostram as cartas para definir o vencedor.' },
  { term: 'Bankroll', description: 'Montante total reservado para jogar poker, separado das finanças pessoais.' },
  { term: 'Blinds', description: 'Apostas obrigatórias feitas por dois jogadores antes das cartas serem distribuídas.' },
  { term: 'Small Blind', description: 'Primeiro jogador à esquerda do botão, faz a aposta obrigatória menor.' },
  { term: 'Big Blind', description: 'Jogador à esquerda do Small Blind, faz a aposta obrigatória completa.' },
  { term: 'Button', description: 'Marcador que indica o dealer da rodada, posição mais vantajosa.' },
  { term: 'UTG', description: 'Under the Gun: primeiro a agir antes do flop, posição difícil.' },
  { term: 'Pre-Flop', description: 'Primeira rodada de apostas, antes das cartas comunitárias.' },
  { term: 'Flop', description: 'As três primeiras cartas comunitárias abertas na mesa.' },
  { term: 'Turn', description: 'A quarta carta comunitária aberta na mesa.' },
  { term: 'River', description: 'A quinta e última carta comunitária aberta na mesa.' },
]; 